### ISSUE TITLE
Breach of MIT license

### ISSUE THREAD

**Issue by BrettMW** [alanshortis/wordpress-boilerplate#1]
The img_resize function included (https://github.com/alanshortis/wordpress-boilerplate/blob/master/wp-content/themes/bp/functions.php#L60-L85) is licensed under the MIT license (https://github.com/BrettMW/img_resize/blob/master/LICENSE) but no copyright/permission notice is included for that code.

To be honest I'm not that worried, but it would be nice if the copyright was included :smile:

**Comment by alanshortis** [comment]
Really really sorry about that - I'll get the notice back on there today.

**Comment by BrettMW** [comment]
Thanks
